### PR TITLE
bugfix: fun.lua:958: attempt to call local 'gen_x' (a nil value)

### PR DESCRIPTION
**Pull request by tom2nonames**

### CODE REVIEW

**Comment by Totktonada** [comment]
The reason is https://github.com/LuaJIT/LuaJIT/issues/584

@igormunkin, can we workaround it on the luafun side to don't break behaviour in any case?

**Comment by igormunkin** [comment]
> @igormunkin, can we workaround it on the luafun side to don't break behaviour in any case?

@Totktonada, unfortunately, there is no other way now but disable JIT for chain: either "globally" in scope of Lua Fun or in the user code the similar way I made in scope of tarantool/tarantool@5fa7ded.

**Comment by Totktonada** [comment]
So if we'll push this `nil` check, we likely will silently feed incorrect results for a caller, right?

**Comment by igormunkin** [comment]
> So if we'll push this `nil` check, we likely will silently feed incorrect results for a caller, right?

Yes. As I mentioned in the issue, `gen_x` is misfetched due to an invalid `i` value, so we don't know whether iterator is exhausted or not at this point.

**Comment by Totktonada** [comment]
Thanks for the clarification!

So the only thing we can do here is waiting for LuaJIT to fix the bug.

**Comment by Totktonada** [comment]
It worth to re-check after https://github.com/LuaJIT/LuaJIT/commit/33e3f4badfde8cd9c202cedd1f4ed9275bc92e7d.

**Comment by igormunkin** [comment]
The issue is resolved in tarantool in 2.9.0-194-g6a420c257 ([6a420c2](https://github.com/tarantool/tarantool/commit/6a420c2)), 2.8.1-142-gfa440119d ([fa44011](https://github.com/tarantool/tarantool/commit/fa44011)), 2.7.2-133-g28bd66a9d ([28bd66a](https://github.com/tarantool/tarantool/commit/28bd66a)), 1.10.10-63-ga0d081f03 ([a0d081f](https://github.com/tarantool/tarantool/commit/a0d081f)).

**Pull request closed without merging**
