### PR TITLE
Added reverse table iterator

### PR DESCRIPTION
**Pull request by HeinrichHartmann**
Hey folks,

I ran into the need of iterating a table in the reverse order. Since I could not
figure out an idiomatic way to do this with the current `fun.lua` - features,
I added a `rev_iter` generator.

Questions:
- Is there a better way to walk through an array in reverse order? If not:
- Do you want to include a feature like that in the library?
- Is this a good name `rev_iter` ?

I am happy to contribute docs + tests if there is interest in pulling this in.

Best regards,
Heinrich

### CODE REVIEW

**Comment by rtsisyk** [comment]
Sorry for the my late reply. See [#31](https://github.com/luafun/luafun/issues/31#issuecomment-277508076) for details.

I think that this patch is OK, but we need to brainstorm a better name for `rev_iter`.

**Comment by HeinrichHartmann** [comment]
c++/std has reverse_iterator: http://en.cppreference.com/w/cpp/iterator/reverse_iterator

So how about `reverse_iter` ? (since the forward one is called `iter`)

**Comment by HeinrichHartmann** [comment]
Added tests and docs.

**Comment by HeinrichHartmann** [comment]
squashed into single commit

**Comment by HeinrichHartmann** [comment]
I need my master branch for more extensive rewrites. Feel free to pull in the d37fcbb.

**Comment by HeinrichHartmann** [comment]
I don't follow. Are you talking about: https://github.com/luafun/luafun/commit/d37fcbbcfcf833e881875a2f30719c23144499f4

I don't see what this has to do with iparis being passed as an argument somewhere.

**Comment by nmattia** [comment]
Hi, did something like this get merged eventually? Can I create an iterator that iterates backwards?

**Comment by anonghuser** [comment]
Since range method allows negative step, it is easy to do this for array `t`:
```
fun.range(#t, 1):map(function (k) return t[k]; end)
```

I think having it as a reverse_iter method that only properly reverses arrays would be bad. What is it supposed to do with non-array iterators? Iterate as-is since "order" is undefined for maps anyway? Fail? Buffer them and reverse? The last one seems the most sensible to me, and may well be worth adding, if/when other buffer-and-sort methods are added. But specifically for arrays it is unnecessary given how short the `range` version is anyway.

**Pull request closed without merging**
